require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/jira_projects", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # JiraProject. As you add validations to JiraProject, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      JiraProject.create! valid_attributes
      get jira_projects_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      jira_project = JiraProject.create! valid_attributes
      get jira_project_url(jira_project)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_jira_project_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      jira_project = JiraProject.create! valid_attributes
      get edit_jira_project_url(jira_project)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new JiraProject" do
        expect {
          post jira_projects_url, params: { jira_project: valid_attributes }
        }.to change(JiraProject, :count).by(1)
      end

      it "redirects to the created jira_project" do
        post jira_projects_url, params: { jira_project: valid_attributes }
        expect(response).to redirect_to(jira_project_url(JiraProject.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new JiraProject" do
        expect {
          post jira_projects_url, params: { jira_project: invalid_attributes }
        }.to change(JiraProject, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post jira_projects_url, params: { jira_project: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested jira_project" do
        jira_project = JiraProject.create! valid_attributes
        patch jira_project_url(jira_project), params: { jira_project: new_attributes }
        jira_project.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the jira_project" do
        jira_project = JiraProject.create! valid_attributes
        patch jira_project_url(jira_project), params: { jira_project: new_attributes }
        jira_project.reload
        expect(response).to redirect_to(jira_project_url(jira_project))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        jira_project = JiraProject.create! valid_attributes
        patch jira_project_url(jira_project), params: { jira_project: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested jira_project" do
      jira_project = JiraProject.create! valid_attributes
      expect {
        delete jira_project_url(jira_project)
      }.to change(JiraProject, :count).by(-1)
    end

    it "redirects to the jira_projects list" do
      jira_project = JiraProject.create! valid_attributes
      delete jira_project_url(jira_project)
      expect(response).to redirect_to(jira_projects_url)
    end
  end
end
