require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/jira_issues", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # JiraIssue. As you add validations to JiraIssue, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      JiraIssue.create! valid_attributes
      get jira_issues_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      jira_issue = JiraIssue.create! valid_attributes
      get jira_issue_url(jira_issue)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_jira_issue_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      jira_issue = JiraIssue.create! valid_attributes
      get edit_jira_issue_url(jira_issue)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new JiraIssue" do
        expect {
          post jira_issues_url, params: { jira_issue: valid_attributes }
        }.to change(JiraIssue, :count).by(1)
      end

      it "redirects to the created jira_issue" do
        post jira_issues_url, params: { jira_issue: valid_attributes }
        expect(response).to redirect_to(jira_issue_url(JiraIssue.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new JiraIssue" do
        expect {
          post jira_issues_url, params: { jira_issue: invalid_attributes }
        }.to change(JiraIssue, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post jira_issues_url, params: { jira_issue: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested jira_issue" do
        jira_issue = JiraIssue.create! valid_attributes
        patch jira_issue_url(jira_issue), params: { jira_issue: new_attributes }
        jira_issue.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the jira_issue" do
        jira_issue = JiraIssue.create! valid_attributes
        patch jira_issue_url(jira_issue), params: { jira_issue: new_attributes }
        jira_issue.reload
        expect(response).to redirect_to(jira_issue_url(jira_issue))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        jira_issue = JiraIssue.create! valid_attributes
        patch jira_issue_url(jira_issue), params: { jira_issue: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested jira_issue" do
      jira_issue = JiraIssue.create! valid_attributes
      expect {
        delete jira_issue_url(jira_issue)
      }.to change(JiraIssue, :count).by(-1)
    end

    it "redirects to the jira_issues list" do
      jira_issue = JiraIssue.create! valid_attributes
      delete jira_issue_url(jira_issue)
      expect(response).to redirect_to(jira_issues_url)
    end
  end
end
