require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/resource_budgets", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ResourceBudget. As you add validations to ResourceBudget, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ResourceBudget.create! valid_attributes
      get resource_budgets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      resource_budget = ResourceBudget.create! valid_attributes
      get resource_budget_url(resource_budget)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_resource_budget_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      resource_budget = ResourceBudget.create! valid_attributes
      get edit_resource_budget_url(resource_budget)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ResourceBudget" do
        expect {
          post resource_budgets_url, params: { resource_budget: valid_attributes }
        }.to change(ResourceBudget, :count).by(1)
      end

      it "redirects to the created resource_budget" do
        post resource_budgets_url, params: { resource_budget: valid_attributes }
        expect(response).to redirect_to(resource_budget_url(ResourceBudget.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ResourceBudget" do
        expect {
          post resource_budgets_url, params: { resource_budget: invalid_attributes }
        }.to change(ResourceBudget, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post resource_budgets_url, params: { resource_budget: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested resource_budget" do
        resource_budget = ResourceBudget.create! valid_attributes
        patch resource_budget_url(resource_budget), params: { resource_budget: new_attributes }
        resource_budget.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the resource_budget" do
        resource_budget = ResourceBudget.create! valid_attributes
        patch resource_budget_url(resource_budget), params: { resource_budget: new_attributes }
        resource_budget.reload
        expect(response).to redirect_to(resource_budget_url(resource_budget))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        resource_budget = ResourceBudget.create! valid_attributes
        patch resource_budget_url(resource_budget), params: { resource_budget: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested resource_budget" do
      resource_budget = ResourceBudget.create! valid_attributes
      expect {
        delete resource_budget_url(resource_budget)
      }.to change(ResourceBudget, :count).by(-1)
    end

    it "redirects to the resource_budgets list" do
      resource_budget = ResourceBudget.create! valid_attributes
      delete resource_budget_url(resource_budget)
      expect(response).to redirect_to(resource_budgets_url)
    end
  end
end
