# This file contains the general configuration information for the
# EngIn application.
EngIn:
  http_debug: true
  redis_server: <%= ENV("ENGIN_REDIS_SERVER") %>
  redis_port: <%= ENV("ENGIN_REDIS_PORT") %>
